# Generated by Django 5.2.4 on 2025-07-24 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_user_options_user_bio_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
